<?php
    $Preguntas = array(
        '
        ',
        '<b>1.</b> Para su contratación fue más importante ser mujer u hombre que sus habilidades profesionales.',
        '<b>2.</b> En su centro de trabajo el proceso de contratación favorece más a personas jóvenes.',
        '<b>3.</b> En el momento de su contratación, su edad fue determinante.',
        '<b>4.</b> Para su contratación fue determinante su apariencia física.',
        '<b>5.</b> En su centro de trabajo las oportunidades de desarrollo laboral solo las reciben unas cuántas personas privilegiadas.',
        '<b>6.</b> En su centro de trabajo mujeres y hombres tienen por igual oportunidades de ascenso y capacitación.',
        '<b>7.</b> En su centro de trabajo se cuenta con programas de capacitación en materia de igualdad laboral y no discriminación.',
        '<b>8.</b> En los últimos 12 meses usted ha participado en programas de capacitación.',
        '<b>9.</b> En su centro de trabajo para lograr la contratación, una promoción o un ascenso cuentan más las recomendaciones que los conocimientos y capacidades de la persona.',
        '<b>10.</b> En su centro de trabajo se ha despedido a alguna mujer por embarazo u orillado a renunciar al regresar de su licencia de maternidad.',
        '<b>11.</b> En su centro de trabajo la competencia por mejores puestos, condiciones laborales o salariales es justas ',
        '<b>12.</b> En su centro de trabajo mujeres y hombres tienen las mismas oportunidades para ocupar puestos de decisión.',
        '<b>13.</b> En su centro de trabajo se cuenta con un sistema de evaluación de desempeño del personal.',
        '<b>14.</b> En los últimos 12 meses le han realizado una evaluación de desempeño.',
        '<b>15.</b> En su centro de trabajo tanto mujeres como hombres tienen las mismas facilidades para atender problemas familiares no previstos.',
        '<b>16.</b> En su centro de trabajo las mujeres embarazadas enfrentan un clima laboral hostil.',
        '<b>17.</b> En su centro de trabajo las personas que se hacen cargo de personas o familiares que requieren cuidados enfrentan un clima laboral hostil.',
        '<b>18.</b> En su centro de trabajo los hombres cuentan con licencia de paternidad por nacimiento o adopción de una hija(o)',
        '<b>19.</b> En su centro de trabajo la licencia de paternidad se otorga por más de cinco días.',
        '<b>20.</b> En su centro de trabajo se  otorgan permisos para atender situaciones familiares como cuidado de hijas e hijos, personas enfermas o personas adultas mayores.',
        '<b>21.</b> En su centro de trabajo existen convenios con prestadores de servicios que contemplen beneficios para el personal tales como: lavanderías, comedores, planchadurías, transporte, entre otros.',
        '<b>22.</b> En su centro de trabajo, si usted decidiera usar las opciones de trabajo flexibles ¿se cuestionaría su compromiso ante su trabajo?',
        '<b>23.</b> En su centro de trabajo usted puede acercarse a su jefa (e) inmediata (o)n para hablar sobre cuestiones relacionadas con horarios que le estén afectando.',
        '<b>24.</b> Usted siente que se le trata con respeto en su trabajo actual.',
        '<b>25.</b> En su centro de trabajo quienes realizan tareas personales para las y los jefes logran privilegios.',
        '<b>26.</b> En su centro de trabajo todas las personas que laboran obtienen un trato digno y decente.',
        '<b>27.</b> En su centro de trabajo las valoraciones que se realizan a sus actividades dependen más de la calidad y responsabilidad que de cualquier otra cuestión personal.',
        '<b>28.</b> En su centro de trabajo, en general hay personas que discriminan, tratan mal o le faltan al respeto a sus compañeras (os), colegas o subordinadas (os)',
        '<b>29.</b> En su centro de trabajo debido a sus características personales hay personas que sufren un trato inferior o de burla.',
        '<b>30.</b> En su centro de trabajo las y los superiores reciben un trato mucho más respetuoso que subordinados (as) y personal administrativo.',
        '<b>31.</b> En su centro de trabajo las y los superiores están abiertos a la comunicación con el personal.',
        '<b>32.</b> En su centro de trabajo se da un trato inferior o discriminatorio a las personas con los más bajos niveles de sueldo.',
        '<b>33.</b> En su centro de trabajo existen campañas de difusión internas de promoción de la igualdad laboral y no discriminación.',
        '<b>34.</b> En su centro de trabajo se toman acciones como: asilamiento de sus compañeras(os), cambio de lugar repentinamente, falta de instrucciones, menosprecio del esfuerzo o propuestas, imposición de tareas sin los medios para realizarlas.',
        '<b>35.</b> En su centro de trabajo las funciones y tareas se transmiten de manera clara y precisa.',
        '<b>36.</b> En su centro de trabajo las cargas de trabajo se distribuyen de acuerdo a la responsabilidad del cargo.',
        '<b>37.</b> Si manifiesto mi preocupación sobre algún asunto relacionado con la igualdad de género o prácticas discriminatorias, se le da seguimiento.',
        '<b>38.</b> En su centro de trabajo ha recibido, comentarios sugestivos o sexistas, bromas ofensivas, miradas obscenas o petición de pláticas indeseables relacionadas con asuntos sexuales.',
        '<b>39.</b> En su centro de trabajo ha recibido proposiciones o peticiones directas o indirectas para establecer una relación sexual.',
        '<b>40.</b> En su centro de trabajo ha vivido contacto físico sexual no deseado.',
        '<b>41.</b> En su centro de trabajo se logran recompensas o incentivos laborales a cambio de favores sexuales.',
        '<b>42.</b> En su centro de trabajo se reciben amenazas con daños o castigos en caso de no acceder a proporcionar  favores sexuales.',
        '<b>43.</b> En su centro de trabajo ha recibido represalias sin razón o amenazas con relación a su permanencia en el trabajo.',
        '<b>44.</b> En caso de que haya sido víctima de acoso u hostigamiento sexual, en su centro de trabajo resolvieron satisfactoriamente su caso al interior o le canalizaron con las autoridades competentes.',
        '<b>45.</b> En caso de ser acosada (o) u hostigada (o) sexual o laboralmente en su centro de trabajo sabe a qué autoridad puede dirigirse para denunciarlo.',
        '<b>46.</b> En su centro de trabajo se cuenta con el espacio, mobiliario y equipo adecuado para personas con discapacidad',
        '<b>47.</b> Considera que las instalaciones de su centro de trabajo son adecuadas y accesibles para personas con discapacidad (rampas, estacionamiento, sanitarios, oficinas, pasillos, escaleras, elevadores, entre otros)',
        '<b>48.</b> En su centro de trabajo se cuenta con los medios tecnológicos y de comunicación accesible para que cualquier persona con discapacidad desempeñe sus actividades de manera óptima.',
        '<b>49.</b> En su centro de trabajo se contemplan mecanismos o políticas de inclusión laboral para personas con discapacidad, personas adultas mayores o con VIH, entre otras.',
        '<b>50.</b> En su centro de trabajo se utiliza lenguaje incluyente y no sexista.',
        '<b>51.</b> En su centro de trabajo hay un ambiente de respeto y no discriminación hacia las diferencias y preferencias sexuales.',
        '<b>52.</b> En su centro de trabajo ha sio testigo de actos discriminatorios por ser mujer u hombre, por edad, apariencia, discapacidad, entre otros.',
        '<b>53.</b> En su centro de trabajo se proporcionan las prestaciones de ley.',
        '<b>54.</b> En su centro de trabajo las y los directivos apoyan la igualdad y no discriminación',
        '<b>55.</b> En su centro de trabajo los mecanismos utilizados para asegurar la igualdad y no discriminación son eficaces.',
        '<b>56.</b> En su centro de trabajo se recibe un salario igual por igual trabajo sin importar sexo, apariencia, edad u otras características personales.'
    );
?>