<?php
    $Querys = array(
        'SELECT COUNT(ID) AS "ENCUESTADOS" FROM ENCUESTADOS
        ',
        'SELECT 
            (SELECT COUNT(P1) FROM BLOQUE1 WHERE P1 = 0 ) AS "SI",
            (SELECT COUNT(P1) FROM BLOQUE1 WHERE P1 = 3 ) AS "NO" 
        ',
        'SELECT 
            (SELECT COUNT(P2) FROM BLOQUE1 WHERE P2 = 0 ) AS "SI",
            (SELECT COUNT(P2) FROM BLOQUE1 WHERE P2 = 3 ) AS "NO" 
        ',
        'SELECT 
            (SELECT COUNT(P3) FROM BLOQUE1 WHERE P3 = 0 ) AS "SI",
            (SELECT COUNT(P3) FROM BLOQUE1 WHERE P3 = 3 ) AS "NO" 
        ',
        'SELECT 
            (SELECT COUNT(P4) FROM BLOQUE1 WHERE P4 = 0 ) AS "SI",
            (SELECT COUNT(P4) FROM BLOQUE1 WHERE P4 = 3 ) AS "NO" 
        ',
        'SELECT 
            (SELECT COUNT(P5) FROM BLOQUE2 WHERE P5 = 3 ) AS "NUNCA",
            (SELECT COUNT(P5) FROM BLOQUE2 WHERE P5 = 2 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P5) FROM BLOQUE2 WHERE P5 = 1 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P5) FROM BLOQUE2 WHERE P5 = 0 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P6) FROM BLOQUE2 WHERE P6 = 0 ) AS "NUNCA",
            (SELECT COUNT(P6) FROM BLOQUE2 WHERE P6 = 1 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P6) FROM BLOQUE2 WHERE P6 = 2 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P6) FROM BLOQUE2 WHERE P6 = 3 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P7) FROM BLOQUE2 WHERE P7 = 0 ) AS "NUNCA",
            (SELECT COUNT(P7) FROM BLOQUE2 WHERE P7 = 1 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P7) FROM BLOQUE2 WHERE P7 = 2 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P7) FROM BLOQUE2 WHERE P7 = 3 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P8) FROM BLOQUE2 WHERE P8 = 0 ) AS "NUNCA",
            (SELECT COUNT(P8) FROM BLOQUE2 WHERE P8 = 1 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P8) FROM BLOQUE2 WHERE P8 = 2 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P8) FROM BLOQUE2 WHERE P8 = 3 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P9) FROM BLOQUE3 WHERE P9 = 3 ) AS "NUNCA",
            (SELECT COUNT(P9) FROM BLOQUE3 WHERE P9 = 2 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P9) FROM BLOQUE3 WHERE P9 = 1 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P9) FROM BLOQUE3 WHERE P9 = 0 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P10) FROM BLOQUE3 WHERE P10 = 3 ) AS "NUNCA",
            (SELECT COUNT(P10) FROM BLOQUE3 WHERE P10 = 2 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P10) FROM BLOQUE3 WHERE P10 = 1 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P10) FROM BLOQUE3 WHERE P10 = 0 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P11) FROM BLOQUE3 WHERE P11 = 0 ) AS "NUNCA",
            (SELECT COUNT(P11) FROM BLOQUE3 WHERE P11 = 1 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P11) FROM BLOQUE3 WHERE P11 = 2 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P11) FROM BLOQUE3 WHERE P11 = 3 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P12) FROM BLOQUE3 WHERE P12 = 0 ) AS "NUNCA",
            (SELECT COUNT(P12) FROM BLOQUE3 WHERE P12 = 1 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P12) FROM BLOQUE3 WHERE P12 = 2 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P12) FROM BLOQUE3 WHERE P12 = 3 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P13) FROM BLOQUE3 WHERE P13 = 0 ) AS "NUNCA",
            (SELECT COUNT(P13) FROM BLOQUE3 WHERE P13 = 1 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P13) FROM BLOQUE3 WHERE P13 = 2 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P13) FROM BLOQUE3 WHERE P13 = 3 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P14) FROM BLOQUE3 WHERE P14 = 0 ) AS "NUNCA",
            (SELECT COUNT(P14) FROM BLOQUE3 WHERE P14 = 1 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P14) FROM BLOQUE3 WHERE P14 = 2 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P14) FROM BLOQUE3 WHERE P14 = 3 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P15) FROM BLOQUE4 WHERE P15 = 0 ) AS "NUNCA",
            (SELECT COUNT(P15) FROM BLOQUE4 WHERE P15 = 1 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P15) FROM BLOQUE4 WHERE P15 = 2 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P15) FROM BLOQUE4 WHERE P15 = 3 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P16) FROM BLOQUE4 WHERE P16 = 3 ) AS "NUNCA",
            (SELECT COUNT(P16) FROM BLOQUE4 WHERE P16 = 2 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P16) FROM BLOQUE4 WHERE P16 = 1 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P16) FROM BLOQUE4 WHERE P16 = 0 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P17) FROM BLOQUE4 WHERE P17 = 3 ) AS "NUNCA",
            (SELECT COUNT(P17) FROM BLOQUE4 WHERE P17 = 2 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P17) FROM BLOQUE4 WHERE P17 = 1 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P17) FROM BLOQUE4 WHERE P17 = 0 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P18) FROM BLOQUE4 WHERE P18 = 0 ) AS "NUNCA",
            (SELECT COUNT(P18) FROM BLOQUE4 WHERE P18 = 1 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P18) FROM BLOQUE4 WHERE P18 = 2 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P18) FROM BLOQUE4 WHERE P18 = 3 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P19) FROM BLOQUE4 WHERE P19 = 0 ) AS "NUNCA",
            (SELECT COUNT(P19) FROM BLOQUE4 WHERE P19 = 1 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P19) FROM BLOQUE4 WHERE P19 = 2 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P19) FROM BLOQUE4 WHERE P19 = 3 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P20) FROM BLOQUE4 WHERE P20 = 0 ) AS "NUNCA",
            (SELECT COUNT(P20) FROM BLOQUE4 WHERE P20 = 1 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P20) FROM BLOQUE4 WHERE P20 = 2 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P20) FROM BLOQUE4 WHERE P20 = 3 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P21) FROM BLOQUE4 WHERE P21 = 0 ) AS "NUNCA",
            (SELECT COUNT(P21) FROM BLOQUE4 WHERE P21 = 1 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P21) FROM BLOQUE4 WHERE P21 = 2 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P21) FROM BLOQUE4 WHERE P21 = 3 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P22) FROM BLOQUE4 WHERE P22 = 3 ) AS "NUNCA",
            (SELECT COUNT(P22) FROM BLOQUE4 WHERE P22 = 2 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P22) FROM BLOQUE4 WHERE P22 = 1 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P22) FROM BLOQUE4 WHERE P22 = 0 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P23) FROM BLOQUE4 WHERE P23 = 0 ) AS "NUNCA",
            (SELECT COUNT(P23) FROM BLOQUE4 WHERE P23 = 1 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P23) FROM BLOQUE4 WHERE P23 = 2 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P23) FROM BLOQUE4 WHERE P23 = 3 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P24) FROM BLOQUE5 WHERE P24 = 0 ) AS "NUNCA",
            (SELECT COUNT(P24) FROM BLOQUE5 WHERE P24 = 1 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P24) FROM BLOQUE5 WHERE P24 = 2 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P24) FROM BLOQUE5 WHERE P24 = 3 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P25) FROM BLOQUE5 WHERE P25 = 3 ) AS "NUNCA",
            (SELECT COUNT(P25) FROM BLOQUE5 WHERE P25 = 2 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P25) FROM BLOQUE5 WHERE P25 = 1 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P25) FROM BLOQUE5 WHERE P25 = 0 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P26) FROM BLOQUE5 WHERE P26 = 0 ) AS "NUNCA",
            (SELECT COUNT(P26) FROM BLOQUE5 WHERE P26 = 1 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P26) FROM BLOQUE5 WHERE P26 = 2 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P26) FROM BLOQUE5 WHERE P26 = 3 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P27) FROM BLOQUE5 WHERE P27 = 0 ) AS "NUNCA",
            (SELECT COUNT(P27) FROM BLOQUE5 WHERE P27 = 1 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P27) FROM BLOQUE5 WHERE P27 = 2 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P27) FROM BLOQUE5 WHERE P27 = 3 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P28) FROM BLOQUE5 WHERE P28 = 3 ) AS "NUNCA",
            (SELECT COUNT(P28) FROM BLOQUE5 WHERE P28 = 2 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P28) FROM BLOQUE5 WHERE P28 = 1 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P28) FROM BLOQUE5 WHERE P28 = 0 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P29) FROM BLOQUE5 WHERE P29 = 3 ) AS "NUNCA",
            (SELECT COUNT(P29) FROM BLOQUE5 WHERE P29 = 2 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P29) FROM BLOQUE5 WHERE P29 = 1 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P29) FROM BLOQUE5 WHERE P29 = 0 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P30) FROM BLOQUE5 WHERE P30 = 3 ) AS "NUNCA",
            (SELECT COUNT(P30) FROM BLOQUE5 WHERE P30 = 2 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P30) FROM BLOQUE5 WHERE P30 = 1 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P30) FROM BLOQUE5 WHERE P30 = 0 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P31) FROM BLOQUE5 WHERE P31 = 0 ) AS "NUNCA",
            (SELECT COUNT(P31) FROM BLOQUE5 WHERE P31 = 1 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P31) FROM BLOQUE5 WHERE P31 = 2 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P31) FROM BLOQUE5 WHERE P31 = 3 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P32) FROM BLOQUE5 WHERE P32 = 3 ) AS "NUNCA",
            (SELECT COUNT(P32) FROM BLOQUE5 WHERE P32 = 2 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P32) FROM BLOQUE5 WHERE P32 = 1 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P32) FROM BLOQUE5 WHERE P32 = 0 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P33) FROM BLOQUE5 WHERE P33 = 0 ) AS "NUNCA",
            (SELECT COUNT(P33) FROM BLOQUE5 WHERE P33 = 1 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P33) FROM BLOQUE5 WHERE P33 = 2 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P33) FROM BLOQUE5 WHERE P33 = 3 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P34) FROM BLOQUE5 WHERE P34 = 3 ) AS "NUNCA",
            (SELECT COUNT(P34) FROM BLOQUE5 WHERE P34 = 2 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P34) FROM BLOQUE5 WHERE P34 = 1 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P34) FROM BLOQUE5 WHERE P34 = 0 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P35) FROM BLOQUE5 WHERE P35 = 0 ) AS "NUNCA",
            (SELECT COUNT(P35) FROM BLOQUE5 WHERE P35 = 1 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P35) FROM BLOQUE5 WHERE P35 = 2 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P35) FROM BLOQUE5 WHERE P35 = 3 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P36) FROM BLOQUE5 WHERE P36 = 0 ) AS "NUNCA",
            (SELECT COUNT(P36) FROM BLOQUE5 WHERE P36 = 1 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P36) FROM BLOQUE5 WHERE P36 = 2 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P36) FROM BLOQUE5 WHERE P36 = 3 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P37) FROM BLOQUE5 WHERE P37 = 0 ) AS "NUNCA",
            (SELECT COUNT(P37) FROM BLOQUE5 WHERE P37 = 1 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P37) FROM BLOQUE5 WHERE P37 = 2 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P37) FROM BLOQUE5 WHERE P37 = 3 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P38) FROM BLOQUE6 WHERE P38 = 0 ) AS "SI",
            (SELECT COUNT(P38) FROM BLOQUE6 WHERE P38 = 3 ) AS "NO" 
        ',
        'SELECT 
            (SELECT COUNT(P39) FROM BLOQUE6 WHERE P39 = 0 ) AS "SI",
            (SELECT COUNT(P39) FROM BLOQUE6 WHERE P39 = 3 ) AS "NO" 
        ',
        'SELECT 
            (SELECT COUNT(P40) FROM BLOQUE6 WHERE P40 = 0 ) AS "SI",
            (SELECT COUNT(P40) FROM BLOQUE6 WHERE P40 = 3 ) AS "NO" 
        ',
        'SELECT 
            (SELECT COUNT(P41) FROM BLOQUE6 WHERE P41 = 0 ) AS "SI",
            (SELECT COUNT(P41) FROM BLOQUE6 WHERE P41 = 3 ) AS "NO" 
        ',
        'SELECT 
            (SELECT COUNT(P42) FROM BLOQUE6 WHERE P42 = 0 ) AS "SI",
            (SELECT COUNT(P42) FROM BLOQUE6 WHERE P42 = 3 ) AS "NO" 
        ',
        'SELECT 
            (SELECT COUNT(P43) FROM BLOQUE6 WHERE P43 = 0 ) AS "SI",
            (SELECT COUNT(P43) FROM BLOQUE6 WHERE P43 = 3 ) AS "NO" 
        ',
        'SELECT 
            (SELECT COUNT(P44) FROM BLOQUE6 WHERE P44 = 3 ) AS "SI",
            (SELECT COUNT(P44) FROM BLOQUE6 WHERE P44 = 0 ) AS "NO" 
        ',
        'SELECT 
            (SELECT COUNT(P45) FROM BLOQUE6 WHERE P45 = 3 ) AS "SI",
            (SELECT COUNT(P45) FROM BLOQUE6 WHERE P45 = 0 ) AS "NO" 
        ',
        'SELECT 
	        (SELECT COUNT(P46) FROM BLOQUE7 WHERE P46 = 0 ) AS "NUNCA",
	        (SELECT COUNT(P46) FROM BLOQUE7 WHERE P46 = 1 ) AS "ALGUNAS VECES",
	        (SELECT COUNT(P46) FROM BLOQUE7 WHERE P46 = 2 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P46) FROM BLOQUE7 WHERE P46 = 3 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P47) FROM BLOQUE7 WHERE P47 = 0 ) AS "NUNCA",
            (SELECT COUNT(P47) FROM BLOQUE7 WHERE P47 = 1 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P47) FROM BLOQUE7 WHERE P47 = 2 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P47) FROM BLOQUE7 WHERE P47 = 3 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P48) FROM BLOQUE7 WHERE P48 = 0 ) AS "NUNCA",
            (SELECT COUNT(P48) FROM BLOQUE7 WHERE P48 = 1 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P48) FROM BLOQUE7 WHERE P48 = 2 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P48) FROM BLOQUE7 WHERE P48 = 3 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P49) FROM BLOQUE7 WHERE P49 = 0 ) AS "NUNCA",
            (SELECT COUNT(P49) FROM BLOQUE7 WHERE P49 = 1 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P49) FROM BLOQUE7 WHERE P49 = 2 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P49) FROM BLOQUE7 WHERE P49 = 3 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P50) FROM BLOQUE7 WHERE P50 = 0 ) AS "NUNCA",
            (SELECT COUNT(P50) FROM BLOQUE7 WHERE P50 = 1 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P50) FROM BLOQUE7 WHERE P50 = 2 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P50) FROM BLOQUE7 WHERE P50 = 3 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P51) FROM BLOQUE8 WHERE P51 = 0 ) AS "NUNCA",
            (SELECT COUNT(P51) FROM BLOQUE8 WHERE P51 = 1 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P51) FROM BLOQUE8 WHERE P51 = 2 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P51) FROM BLOQUE8 WHERE P51 = 3 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P52) FROM BLOQUE8 WHERE P52 = 3 ) AS "NUNCA",
            (SELECT COUNT(P52) FROM BLOQUE8 WHERE P52 = 2 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P52) FROM BLOQUE8 WHERE P52 = 1 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P52) FROM BLOQUE8 WHERE P52 = 0 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P53) FROM BLOQUE9 WHERE P53 = 0 ) AS "NUNCA",
            (SELECT COUNT(P53) FROM BLOQUE9 WHERE P53 = 1 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P53) FROM BLOQUE9 WHERE P53 = 2 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P53) FROM BLOQUE9 WHERE P53 = 3 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P54) FROM BLOQUE9 WHERE P54 = 0 ) AS "NUNCA",
            (SELECT COUNT(P54) FROM BLOQUE9 WHERE P54 = 1 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P54) FROM BLOQUE9 WHERE P54 = 2 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P54) FROM BLOQUE9 WHERE P54 = 3 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P55) FROM BLOQUE9 WHERE P55 = 0 ) AS "NUNCA",
            (SELECT COUNT(P55) FROM BLOQUE9 WHERE P55 = 1 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P55) FROM BLOQUE9 WHERE P55 = 2 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P55) FROM BLOQUE9 WHERE P55 = 3 ) AS "SIEMPRE" 
        ',
        'SELECT 
            (SELECT COUNT(P56) FROM BLOQUE9 WHERE P56 = 0 ) AS "NUNCA",
            (SELECT COUNT(P56) FROM BLOQUE9 WHERE P56 = 1 ) AS "ALGUNAS VECES",
            (SELECT COUNT(P56) FROM BLOQUE9 WHERE P56 = 2 ) AS "CON FRECUENCIA",
            (SELECT COUNT(P56) FROM BLOQUE9 WHERE P56 = 3 ) AS "SIEMPRE" 
        ',
        'SELECT
            (SELECT COUNT(SEXO) FROM ENCUESTADOS WHERE SEXO = "Hombre" ) AS "Hombre",
            (SELECT COUNT(SEXO) FROM ENCUESTADOS WHERE SEXO = "Mujer" ) AS "Mujer",
            (SELECT "") AS "atr3",
            (SELECT "") AS "atr4",
            (SELECT "") AS "atr5",
            (SELECT "") AS "atr6",
            (SELECT "") AS "atr7",
            (SELECT "") AS "atr8"
        ',
        'SELECT
            (SELECT COUNT(EDAD) FROM ENCUESTADOS WHERE EDAD = "15-29" ) AS "15-29",
            (SELECT COUNT(EDAD) FROM ENCUESTADOS WHERE EDAD = "30-39" ) AS "30-39",
            (SELECT COUNT(EDAD) FROM ENCUESTADOS WHERE EDAD = "40-49" ) AS "40-49",
            (SELECT COUNT(EDAD) FROM ENCUESTADOS WHERE EDAD = "50-59" ) AS "50-59",
            (SELECT COUNT(EDAD) FROM ENCUESTADOS WHERE EDAD = "60 y mas" ) AS "60 y mas",
            (SELECT "") AS "atr6",
            (SELECT "") AS "atr7",
            (SELECT "") AS "atr8"
        ',
        'SELECT
            (SELECT COUNT(EDOCV) FROM ENCUESTADOS WHERE EDOCV = "Soltera (o)" ) AS "Soltera (o)",
            (SELECT COUNT(EDOCV) FROM ENCUESTADOS WHERE EDOCV = "Casada (o)" ) AS "Casada (o)",
            (SELECT COUNT(EDOCV) FROM ENCUESTADOS WHERE EDOCV = "Union libre" ) AS "Union libre",
            (SELECT COUNT(EDOCV) FROM ENCUESTADOS WHERE EDOCV = "Divorciada (o)" ) AS "Divorciada (o)",
            (SELECT COUNT(EDOCV) FROM ENCUESTADOS WHERE EDOCV = "Viuda (o)" ) AS "Viuda (o)",
            (SELECT "") AS "atr6",
            (SELECT "") AS "atr7",
            (SELECT "") AS "atr8"
        ',
        'SELECT
            (SELECT COUNT(ANTI) FROM ENCUESTADOS WHERE ANTI = "Menos de un ano" ) AS "Menos de un ano",
            (SELECT COUNT(ANTI) FROM ENCUESTADOS WHERE ANTI = "De 1 a 3 anos" ) AS "De 1 a 3 anos",
            (SELECT COUNT(ANTI) FROM ENCUESTADOS WHERE ANTI = "De 4 a 9 anos" ) AS "De 4 a 9 anos",
            (SELECT COUNT(ANTI) FROM ENCUESTADOS WHERE ANTI = "Mas de 10 anos" ) AS "Mas de 10 anos",
            (SELECT "") AS "atr5",
            (SELECT "") AS "atr6",
            (SELECT "") AS "atr7",
            (SELECT "") AS "atr8"
        ',
        'SELECT
            (SELECT COUNT(ESCO) FROM ENCUESTADOS WHERE ESCO = "Sin escolaridad" ) AS "Sin escolaridad",
            (SELECT COUNT(ESCO) FROM ENCUESTADOS WHERE ESCO = "Primaria" ) AS "Primaria",
            (SELECT COUNT(ESCO) FROM ENCUESTADOS WHERE ESCO = "Secundaria" ) AS "Secundaria",
            (SELECT COUNT(ESCO) FROM ENCUESTADOS WHERE ESCO = "Bachillerato o preparatoria" ) AS "Bachillerato o preparatoria",
            (SELECT COUNT(ESCO) FROM ENCUESTADOS WHERE ESCO = "Carrera tecnica" ) AS "Carrera tecnica",
            (SELECT COUNT(ESCO) FROM ENCUESTADOS WHERE ESCO = "Licenciatura" ) AS "Licenciatura",
            (SELECT COUNT(ESCO) FROM ENCUESTADOS WHERE ESCO = "Maestria " ) AS "Maestria ",
            (SELECT COUNT(ESCO) FROM ENCUESTADOS WHERE ESCO = "Doctorado" ) AS "Doctorado"
        ',
        'SELECT
            (SELECT COUNT(PLAZA) FROM ENCUESTADOS WHERE PLAZA = "Base" ) AS "Base ",
            (SELECT COUNT(PLAZA) FROM ENCUESTADOS WHERE PLAZA = "Honorarios" ) AS "Honorarios",
            (SELECT COUNT(PLAZA) FROM ENCUESTADOS WHERE PLAZA = "Confianza" ) AS "Confianza",
            (SELECT COUNT(PLAZA) FROM ENCUESTADOS WHERE PLAZA = "Interinato" ) AS "Interinato",
            (SELECT COUNT(PLAZA) FROM ENCUESTADOS WHERE PLAZA LIKE "%Otro -%" ) AS "Otro",
            (SELECT "") AS "atr6",
            (SELECT "") AS "atr7",
            (SELECT "") AS "atr8"
        ',
        'SELECT
            (SELECT COUNT(DISCA) FROM ENCUESTADOS WHERE DISCA = "NO" ) AS "NO",
            (SELECT COUNT(DISCA) FROM ENCUESTADOS WHERE DISCA = "Intelectual" ) AS "Intelectual",
            (SELECT COUNT(DISCA) FROM ENCUESTADOS WHERE DISCA = "Motriz" ) AS "Motriz",
            (SELECT COUNT(DISCA) FROM ENCUESTADOS WHERE DISCA = "Auditiva" ) AS "Auditiva",
            (SELECT COUNT(DISCA) FROM ENCUESTADOS WHERE DISCA = "Visual" ) AS "Visual",
            (SELECT "") AS "atr6",
            (SELECT "") AS "atr7",
            (SELECT "") AS "atr8"
        ',
        'SELECT
            (SELECT COUNT(SECTOR) FROM ENCUESTADOS WHERE SECTOR = "NO" ) AS "NO",
            (SELECT COUNT(SECTOR) FROM ENCUESTADOS WHERE SECTOR = "De la diversidad sexual" ) AS "De la diversidad sexual",
            (SELECT COUNT(SECTOR) FROM ENCUESTADOS WHERE SECTOR = "Indigenas" ) AS "Indigenas",
            (SELECT COUNT(SECTOR) FROM ENCUESTADOS WHERE SECTOR = "Afrodescendientes" ) AS "Afrodescendientes",
            (SELECT COUNT(SECTOR) FROM ENCUESTADOS WHERE SECTOR = "Adultos mayores" ) AS "Adultos mayores",
            (SELECT COUNT(SECTOR) FROM ENCUESTADOS WHERE SECTOR LIKE "%Otro -%" ) AS "Otro",
            (SELECT "") AS "atr7",
            (SELECT "") AS "atr8"
        '
    );
?>